name: performance_interceptor
description: Intereceptors for Firebase peformance http Metric.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_performance: ^0.3.1+5

  http_interceptor: ">=0.1.1 <2.0.0"
  dio: ">=3.0.8 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: